INSERT INTO workouts (name, description, muscle_group, difficulty, duration_minutes, equipment, created_at)
VALUES
    ('Push Up', 'Classic upper body exercise for chest and triceps strength.', 'CHEST', 'BEGINNER', 15, 'None', CURRENT_TIMESTAMP),
    ('Pull Up', 'Bodyweight exercise targeting the back and biceps.', 'BACK', 'ADVANCED', 20, 'Pull-up Bar', CURRENT_TIMESTAMP),
    ('Squat', 'Lower body compound movement for legs and glutes.', 'LEGS', 'BEGINNER', 25, 'None', CURRENT_TIMESTAMP),
    ('Deadlift', 'Full body strength exercise focusing on posterior chain.', 'BACK', 'ADVANCED', 35, 'Barbell', CURRENT_TIMESTAMP),
    ('Bench Press', 'Popular chest exercise using a barbell.', 'CHEST', 'INTERMEDIATE', 30, 'Barbell', CURRENT_TIMESTAMP),
    ('Shoulder Press', 'Overhead pressing movement for shoulders.', 'SHOULDERS', 'INTERMEDIATE', 25, 'Dumbbells', CURRENT_TIMESTAMP),
    ('Bicep Curl', 'Isolation exercise for biceps development.', 'ARMS', 'BEGINNER', 15, 'Dumbbells', CURRENT_TIMESTAMP),
    ('Tricep Dips', 'Bodyweight movement targeting triceps.', 'ARMS', 'INTERMEDIATE', 20, 'Bench', CURRENT_TIMESTAMP),
    ('Plank', 'Core stabilization exercise.', 'CORE', 'BEGINNER', 10, 'None', CURRENT_TIMESTAMP),
    ('Russian Twist', 'Rotational core exercise for obliques.', 'CORE', 'INTERMEDIATE', 15, 'Medicine Ball', CURRENT_TIMESTAMP),
    ('Lunges', 'Single-leg exercise improving balance and strength.', 'LEGS', 'BEGINNER', 20, 'None', CURRENT_TIMESTAMP),
    ('Leg Press', 'Machine exercise for quadriceps and glutes.', 'LEGS', 'INTERMEDIATE', 30, 'Leg Press Machine', CURRENT_TIMESTAMP),
    ('Lat Pulldown', 'Machine-based back strengthening exercise.', 'BACK', 'BEGINNER', 20, 'Cable Machine', CURRENT_TIMESTAMP),
    ('Chest Fly', 'Isolation movement for chest muscles.', 'CHEST', 'INTERMEDIATE', 20, 'Dumbbells', CURRENT_TIMESTAMP),
    ('Burpees', 'High-intensity full body exercise.', 'FULL_BODY', 'ADVANCED', 15, 'None', CURRENT_TIMESTAMP),
    ('Mountain Climbers', 'Cardio-focused core movement.', 'CORE', 'INTERMEDIATE', 12, 'None', CURRENT_TIMESTAMP),
    ('Jump Rope', 'Cardio workout improving endurance.', 'FULL_BODY', 'BEGINNER', 20, 'Jump Rope', CURRENT_TIMESTAMP),
    ('Box Jumps', 'Explosive plyometric exercise.', 'LEGS', 'ADVANCED', 18, 'Plyo Box', CURRENT_TIMESTAMP),
    ('Hammer Curl', 'Bicep variation focusing on forearms.', 'ARMS', 'BEGINNER', 15, 'Dumbbells', CURRENT_TIMESTAMP),
    ('Skull Crushers', 'Tricep isolation exercise with barbell.', 'ARMS', 'INTERMEDIATE', 18, 'EZ Bar', CURRENT_TIMESTAMP),
    ('Side Plank', 'Core exercise targeting obliques.', 'CORE', 'INTERMEDIATE', 10, 'None', CURRENT_TIMESTAMP),
    ('Seated Row', 'Cable exercise for upper back muscles.', 'BACK', 'INTERMEDIATE', 25, 'Cable Machine', CURRENT_TIMESTAMP),
    ('Incline Bench Press', 'Upper chest focused pressing exercise.', 'CHEST', 'INTERMEDIATE', 30, 'Barbell', CURRENT_TIMESTAMP),
    ('Front Raise', 'Shoulder isolation movement.', 'SHOULDERS', 'BEGINNER', 15, 'Dumbbells', CURRENT_TIMESTAMP),
    ('Lateral Raise', 'Exercise for shoulder width development.', 'SHOULDERS', 'BEGINNER', 15, 'Dumbbells', CURRENT_TIMESTAMP),
    ('Face Pull', 'Rear delt and posture strengthening exercise.', 'SHOULDERS', 'INTERMEDIATE', 20, 'Cable Machine', CURRENT_TIMESTAMP),
    ('Hip Thrust', 'Glute-focused lower body exercise.', 'LEGS', 'INTERMEDIATE', 25, 'Barbell', CURRENT_TIMESTAMP),
    ('Calf Raises', 'Isolation movement for calf muscles.', 'LEGS', 'BEGINNER', 12, 'None', CURRENT_TIMESTAMP),
    ('Arnold Press', 'Advanced shoulder pressing exercise.', 'SHOULDERS', 'ADVANCED', 25, 'Dumbbells', CURRENT_TIMESTAMP),
    ('Cable Crunch', 'Weighted abdominal exercise.', 'CORE', 'INTERMEDIATE', 15, 'Cable Machine', CURRENT_TIMESTAMP),
    ('Farmer Walk', 'Grip and full body endurance exercise.', 'FULL_BODY', 'INTERMEDIATE', 20, 'Dumbbells', CURRENT_TIMESTAMP),
    ('Kettlebell Swing', 'Dynamic movement improving power and cardio.', 'FULL_BODY', 'INTERMEDIATE', 18, 'Kettlebell', CURRENT_TIMESTAMP),
    ('Battle Ropes', 'High intensity cardio and shoulder workout.', 'FULL_BODY', 'ADVANCED', 15, 'Battle Ropes', CURRENT_TIMESTAMP),
    ('Step Ups', 'Leg strengthening exercise using a platform.', 'LEGS', 'BEGINNER', 20, 'Bench', CURRENT_TIMESTAMP),
    ('T-Bar Row', 'Heavy rowing exercise for back thickness.', 'BACK', 'ADVANCED', 30, 'T-Bar Machine', CURRENT_TIMESTAMP),
    ('Pec Deck Fly', 'Machine chest isolation movement.', 'CHEST', 'BEGINNER', 18, 'Pec Deck Machine', CURRENT_TIMESTAMP),
    ('Reverse Crunch', 'Lower abdominal focused core exercise.', 'CORE', 'BEGINNER', 12, 'None', CURRENT_TIMESTAMP),
    ('Good Morning', 'Posterior chain strengthening movement.', 'BACK', 'ADVANCED', 25, 'Barbell', CURRENT_TIMESTAMP),
    ('Wall Sit', 'Static endurance exercise for legs.', 'LEGS', 'BEGINNER', 10, 'None', CURRENT_TIMESTAMP),
    ('Bear Crawl', 'Functional full body movement.', 'FULL_BODY', 'INTERMEDIATE', 15, 'None', CURRENT_TIMESTAMP),
    ('Chin Up', 'Upper body pulling exercise targeting biceps.', 'BACK', 'ADVANCED', 20, 'Pull-up Bar', CURRENT_TIMESTAMP),
    ('Single Arm Row', 'Unilateral back exercise with dumbbell.', 'BACK', 'BEGINNER', 20, 'Dumbbells', CURRENT_TIMESTAMP),
    ('Decline Push Up', 'Advanced push-up variation for upper chest.', 'CHEST', 'INTERMEDIATE', 15, 'Bench', CURRENT_TIMESTAMP),
    ('Hanging Leg Raise', 'Core exercise focusing on lower abs.', 'CORE', 'ADVANCED', 15, 'Pull-up Bar', CURRENT_TIMESTAMP),
    ('Goblet Squat', 'Squat variation using a kettlebell.', 'LEGS', 'BEGINNER', 20, 'Kettlebell', CURRENT_TIMESTAMP),
    ('Thrusters', 'Full body movement combining squat and press.', 'FULL_BODY', 'ADVANCED', 20, 'Dumbbells', CURRENT_TIMESTAMP),
    ('Cable Lateral Raise', 'Cable-based shoulder isolation exercise.', 'SHOULDERS', 'INTERMEDIATE', 18, 'Cable Machine', CURRENT_TIMESTAMP),
    ('Preacher Curl', 'Strict bicep isolation movement.', 'ARMS', 'INTERMEDIATE', 20, 'Preacher Bench', CURRENT_TIMESTAMP),
    ('Diamond Push Up', 'Push-up variation emphasizing triceps.', 'ARMS', 'INTERMEDIATE', 15, 'None', CURRENT_TIMESTAMP),
    ('Superman Hold', 'Lower back strengthening exercise.', 'BACK', 'BEGINNER', 10, 'None', CURRENT_TIMESTAMP);